### ISSUE TITLE
3_Testing_Starter README.md instruction incorrect 

### ISSUE THREAD

**Issue by punsoca** [udacity/nd0044-c2-API-Development-and-Documentation-exercises#4]
In Trivia app Lesson 4 Topic 3 Exercise it says 

**Note**: In this testing exercise, we will run our tests on a new database "bookshelf_test" with the same data.

Yet the instructions are not written correctly in the README.md file.  

Lines 2, 3, 4 , 6, 7  below should reference bookshelf_test, NOT bookshelf.  Note that Line 8 CORRECTLY reference bookshelf_test.  Please correct it.  Newbies might get confused.

```
1 # Linux users
2 su - postgres bash -c "dropdb bookshelf"   
3 su - postgres bash -c "createdb bookshelf"
4 su - postgres bash -c "psql bookshelf < /path/to/backend/books.psql"

# Mac users - local workspace
5 psql postgres
6 dropdb bookshelf
7 createdb bookshelf
8 psql bookshelf_test < books.psql

```

**Comment by ronny-udacity** [comment]
Thanks for reporting this issue. The README file has been updated.
